# Generated by Django 3.2.8 on 2022-01-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=120)),
                ('CCategory_Pic', models.ImageField(default='', upload_to='static/category/')),
                ('C_Add_Date', models.DateField()),
            ],
        ),
    ]
