# Generated by Django 3.2.8 on 2022-01-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='C_Add_Date',
            new_name='CDate',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='CCategory_Pic',
            new_name='CPic',
        ),
    ]
