# Generated by Django 3.2.8 on 2022-01-20 21:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_notification_slider_videonews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ndes',
            field=tinymce.models.HTMLField(),
        ),
    ]
