# Generated by Django 3.2.8 on 2022-01-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ncity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.city'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='vcity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.city'),
        ),
    ]
